### ISSUE TITLE
[WARNING] Error injecting: org.springframework.build.aws.maven.SimpleStorageServiceWagon

### ISSUE THREAD

**Issue by daviswalker** [spring-attic/aws-maven#18]
As of 5.0.0 I get the following error. 4.x does not give this error, although I can't prove it works because I'm getting an "access denied" error as per a previously-filed issue. It looked like upgrading to 5.0.0 was necessary to get the password to be recognized, but then I ran into this.

[WARNING] Error injecting: org.springframework.build.aws.maven.SimpleStorageServiceWagon
java.lang.TypeNotPresentException: Type org.springframework.build.aws.maven.SimpleStorageServiceWagon not present
    at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
    at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
    at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
    at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)

**Comment by nebhale** [comment]
This was the result of nothing more than a version update?  The `<extension/>` declaration hasn't changed?

**Comment by ebaxt** [comment]
Have you tried updating the `maven-deploy-plugin` to the latest version?

**Comment by mcacker** [comment]
Check your JDK version.  You haven't included the whole stacktrace here, but I suspect that if you did it would indicate that the class file version was incompatible with the plugin.  You need at least JDK 7
