### ISSUE TITLE
GetBucketLocation permission

### ISSUE THREAD

**Issue by splix** [spring-attic/aws-maven#30]
Plugin also need permission for `s3:GetBucketLocation` on selected bucket, in addition to `s3:ListBucket`

Without this permission it fails with:

```
aused by: com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: *******, AWS Error Code: AccessDenied, AWS Error Message: Access Denied, S3 Extended Request ID: *****************
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:773)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:417)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3384)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3336)
    at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:669)
    at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:677)
    at org.springframework.build.aws.maven.SimpleStorageServiceWagon.connectToRepository(SimpleStorageServiceWagon.java:86)
    at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:146)
    at org.eclipse.aether.connector.wagon.WagonRepositoryConnector.connectWagon(WagonRepositoryConnector.java:400)
```

**Comment by splix** [comment]
https://github.com/spring-projects/aws-maven/blob/5.0.0.RELEASE/src/main/java/org/springframework/build/aws/maven/SimpleStorageServiceWagon.java#L86

**Comment by stoldio** [comment]
Confirmed, seems like a documentation issue; nothing is mentioned about `GetBucketLocation` permission.
