### ISSUE TITLE
Failed to deploy site due to handling of local directories?

### ISSUE THREAD

**Issue by jdolan** [spring-attic/aws-maven#40]
I've configured this wagon for all distribution management channels, including site:

``` <distributionManagement>
        <repository>
            <id>aws-release</id>
            <url>s3://reel-web-service/release</url>
        </repository>
        <snapshotRepository>
            <id>aws-snapshot</id>
            <url>s3://reel-web-service/snapshot</url>
        </snapshotRepository>
        <site>
            <id>aws-site</id>
            <url>s3://reel-web-service/site</url>
        </site>
    </distributionManagement>
```

Deploying of snapshots (and presumably releases) works fine. However, when running `mvn site:deploy`, the process creates the `site` folder in the target bucket, but fails to create `apidocs` due to what I believe to be a local directory recursion issue:

```
[DEBUG] File name has no extension, mime type cannot be recognised for: apidocs
 Transfer error: org.apache.maven.wagon.ResourceDoesNotExistException: Cannot read file from '/Users/jdolan/Coding/reel-web-service-java/target/site/apidocs'
s3://reel-web-service/site/ - Session: Disconnecting  
s3://reel-web-service/site/ - Session: Logged off
s3://reel-web-service/site/ - Session: Disconnected
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.904 s
[INFO] Finished at: 2015-09-15T09:44:58-04:00
[INFO] Final Memory: 22M/307M
[INFO] ------------------------------------------------------------------------
[DEBUG] Connection manager is shutting down
[DEBUG] Reaper thread: 
java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep(Native Method)
    at com.amazonaws.http.IdleConnectionReaper.run(IdleConnectionReaper.java:112)
[DEBUG] Shutting down reaper thread.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy (default-cli) on project reel-web-service: Error uploading site: Cannot read file from '/Users/jdolan/Coding/reel-web-service-java/target/site/apidocs': /Users/jdolan/Coding/reel-web-service-java/target/site/apidocs (Is a directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy (default-cli) on project reel-web-service: Error uploading site
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
    at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.push(AbstractDeployMojo.java:454)
    at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:323)
    at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:284)
    at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.execute(AbstractDeployMojo.java:166)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Cannot read file from '/Users/jdolan/Coding/reel-web-service-java/target/site/apidocs'
    at org.springframework.build.aws.maven.SimpleStorageServiceWagon.putResource(SimpleStorageServiceWagon.java:189)
    at org.springframework.build.aws.maven.AbstractWagon.put(AbstractWagon.java:227)
    at org.springframework.build.aws.maven.AbstractWagon.putDirectory(AbstractWagon.java:242)
    at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.push(AbstractDeployMojo.java:441)
    ... 25 more
Caused by: java.io.FileNotFoundException: /Users/jdolan/Coding/reel-web-service-java/target/site/apidocs (Is a directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at org.springframework.build.aws.maven.TransferProgressFileInputStream.<init>(TransferProgressFileInputStream.java:29)
    at org.springframework.build.aws.maven.SimpleStorageServiceWagon.putResource(SimpleStorageServiceWagon.java:183)
    ... 28 more
[DEBUG] Connection 0.0.0.0:62088<->54.231.168.21:443 closed
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[DEBUG] Connection 0.0.0.0:62089<->54.231.160.65:443 closed
[DEBUG] Connection 0.0.0.0:62088<->54.231.168.21:443 closed
[DEBUG] Connection 0.0.0.0:62089<->54.231.160.65:443 closed
[DEBUG] Connection manager shut down
```

This, despite the fact that `target/site/apidocs` is present, readable, and full of Javadocs. Really strange behavior. Anyone seen this before?

**Comment by rehevkor5** [comment]
Yes. This appears to be due to `AbstractWagon#putDirectory` passing all results of `File#listFiles()` to `put()`, despite the fact that `listFiles()` returns entries for both files and folders.
